import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:latlong2/latlong.dart';

import 'package:dmm_delivery/models/run_stop.dart';
import 'package:dmm_delivery/services/depot_locator.dart';
import 'package:dmm_delivery/widgets/route_preview_map.dart';
import 'package:dmm_delivery/widgets/stop_card.dart';

RunStop _stop(String id, double lat, double lng, List<StopItem> items) => RunStop(
  id: id,
  seqOrder: 0,
  customerName: 'Customer $id',
  address: '$id Somewhere St',
  location: LatLng(lat, lng),
  items: items,
);

StopItem _item(String code, String product, int qty, {int loose = 0}) =>
    StopItem(code: code, product: product, quantity: qty, crates: 0, loose: loose);

void main() {
  group('milkTotals', () {
    // Numbers taken from the real "South Runsheet 14_07_2026" export, whose
    // first three stops are 3x code 80, then 10x code 80 + 2x code 90, then
    // 3x code 10.
    final stops = [
      _stop('a', -45.87, 170.48, [_item('80', '1 L Standard Milk', 3)]),
      _stop('b', -45.88, 170.49, [_item('80', '1 L Standard Milk', 10), _item('90', '1 L Trim Milk', 2)]),
      _stop('c', -45.89, 170.50, [_item('10', '2 L Standard Milk', 3)]),
    ];

    test('aggregates each product across every stop, heaviest first', () {
      final totals = milkTotals(stops);

      expect(totals.map((t) => t.code), ['80', '10', '90']);
      expect(totals.first.product, '1 L Standard Milk');
      expect(totals.first.quantity, 13);
      expect(totals[1].quantity, 3);
      expect(totals[2].quantity, 2);
    });

    test('is independent of stop order - the van load cannot change when the '
        'route is resequenced', () {
      final forward = milkTotals(stops);
      final reversed = milkTotals(stops.reversed);

      expect({for (final t in reversed) t.code: t.quantity}, {for (final t in forward) t.code: t.quantity});
    });

    test('carries loose units through', () {
      final totals = milkTotals([
        _stop('d', -45.87, 170.48, [_item('159', '1l Oat Milk', 1, loose: 1)]),
      ]);

      expect(totals.single.loose, 1);
    });

    test('sums unit count per stop', () {
      expect(stops[1].unitCount, 12);
    });

    test('is empty for stops with no product lines', () {
      expect(milkTotals([_stop('e', -45.87, 170.48, const [])]), isEmpty);
    });
  });

  group('DepotLocator.addressKey', () {
    test('matches the backend firestore_paths.address_key normalization', () {
      // sha256 of "24 donald street, kaikorai valley, dunedin 9011" (trimmed
      // and lowercased). Generated by the backend itself:
      //   python -c "from dmm_delivery.firestore_paths import address_key; \
      //              print(address_key('24 Donald Street, Kaikorai Valley, Dunedin 9011'))"
      // If this test fails, the two repos have drifted apart on address
      // normalization and the depot pin will silently stop resolving.
      const expected = '1a0758b7cf5ebd95e98cc97e0726d21de8cae9520551d81cc624bc5699c0981f';

      expect(
        DepotLocator.addressKey('  24 Donald Street, Kaikorai Valley, Dunedin 9011  '),
        DepotLocator.addressKey('24 donald street, kaikorai valley, dunedin 9011'),
      );
      expect(DepotLocator.addressKey('24 Donald Street, Kaikorai Valley, Dunedin 9011'), expected);
    });
  });

  group('RoutePreviewMap', () {
    Future<List<LatLng>> pumpAndReadLine(
      WidgetTester tester, {
      required List<RunStop> stops,
      LatLng? depot,
    }) async {
      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: SizedBox(
              width: 400,
              height: 400,
              child: RoutePreviewMap(stops: stops, depot: depot),
            ),
          ),
        ),
      );
      await tester.pump();
      final layer = tester.widget<PolylineLayer>(find.byType(PolylineLayer));
      return layer.polylines.single.points;
    }

    testWidgets('a pin reports which stop was tapped', (tester) async {
      // The review screen's pins were inert while the confirmed route
      // screen's were tappable - backwards, since this is the screen where
      // an owner is deciding whether a stop belongs on the run at all.
      final tapped = <int>[];
      final pinned = [
        _stop('a', -45.87, 170.48, const []),
        _stop('b', -45.88, 170.49, const []),
      ];

      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: SizedBox(
              width: 400,
              height: 400,
              child: RoutePreviewMap(stops: pinned, onStopTap: tapped.add),
            ),
          ),
        ),
      );
      await tester.pump();

      // By index, not by identity: the callback carries the position in the
      // list the owner is looking at, which is what the sheet titles itself
      // with and what removal indexes into.
      await tester.tap(find.byType(StopPin).last);
      await tester.pump();

      expect(tapped, [1]);
    });

    final stops = [
      _stop('a', -45.87, 170.48, const []),
      _stop('b', -45.88, 170.49, const []),
      _stop('c', -45.89, 170.50, const []),
    ];
    const depot = LatLng(-45.8600, 170.4700);

    testWidgets('starts and ends the route at the depot', (tester) async {
      final points = await pumpAndReadLine(tester, stops: stops, depot: depot);

      expect(points.first, depot);
      expect(points.last, depot);
      expect(points.length, stops.length + 2);
    });

    testWidgets('follows the order the stops are given in, so a reorder '
        'redraws the line', (tester) async {
      final forward = await pumpAndReadLine(tester, stops: stops, depot: depot);
      final moved = [stops[2], stops[0], stops[1]];
      final after = await pumpAndReadLine(tester, stops: moved, depot: depot);

      expect(forward.sublist(1, 4), [stops[0].location, stops[1].location, stops[2].location]);
      expect(after.sublist(1, 4), [stops[2].location, stops[0].location, stops[1].location]);
    });

    testWidgets('omits the depot legs when the depot is unknown', (tester) async {
      final points = await pumpAndReadLine(tester, stops: stops);

      expect(points.length, stops.length);
      expect(points.first, stops.first.location);
    });
  });

  group('reordering', _reorderTests);

  group('StopCard shows what to deliver', () {
    // The real "Dynes Transport Amenities" stop from the South Runsheet
    // 14_07_2026 export: two product lines, 12 units in total.
    final dynes = _stop('5440.1', -45.87, 170.48, [
      _item('80', '1 L Standard Milk', 10),
      _item('90', '1 L Trim Milk', 2),
    ]);

    Future<void> pumpCard(WidgetTester tester, RunStop stop) => tester.pumpWidget(
      MaterialApp(
        home: Scaffold(body: StopCard(stop: stop, position: 2)),
      ),
    );

    testWidgets('renders one chip per product line, with quantities', (tester) async {
      await pumpCard(tester, dynes);

      expect(find.text('10 × 1 L Standard Milk'), findsOneWidget);
      expect(find.text('2 × 1 L Trim Milk'), findsOneWidget);
    });

    testWidgets('shows the run sheet sub-total for the stop', (tester) async {
      await pumpCard(tester, dynes);

      expect(find.text('12 units'), findsOneWidget);
    });

    testWidgets('still shows who and where', (tester) async {
      await pumpCard(tester, dynes);

      expect(find.text('Customer 5440.1'), findsOneWidget);
      expect(find.text('5440.1 Somewhere St'), findsOneWidget);
    });

    testWidgets('flags a stop that carries no products rather than rendering '
        'an empty card', (tester) async {
      await pumpCard(tester, _stop('x', -45.87, 170.48, const []));

      expect(find.text('No products listed on the sheet'), findsOneWidget);
      expect(find.textContaining('units'), findsNothing);
    });

    test('one product line reads the same everywhere it appears', () {
      expect(_item('80', '1 L Standard Milk', 10).label, '10 × 1 L Standard Milk');
      expect(dynes.itemsSummary, '10 × 1 L Standard Milk · 2 × 1 L Trim Milk');
      expect(_stop('y', -45.87, 170.48, const []).itemsSummary, isEmpty);
    });
  });
}

/// Mirrors how RunSheetReviewScreen wires its list: the reorder key sits on
/// the direct child the builder returns, the whole row is a long-press drag
/// listener, and RoutePreviewMap is rebuilt from the same (mutable) order.
///
/// This exists to pin the two traps that make a reorderable list of cards
/// misbehave in ways that look like the list "not working":
///   * a key nested inside the returned widget instead of on it, which
///     throws "Every item of ReorderableListView must have a key";
///   * re-applying the `newIndex -= 1` fixup on top of onReorderItem, which
///     already does it - the stop then lands one slot short.
class _ReorderHarness extends StatefulWidget {
  const _ReorderHarness({required this.stops, required this.depot});

  final List<RunStop> stops;
  final LatLng depot;

  @override
  State<_ReorderHarness> createState() => _ReorderHarnessState();
}

class _ReorderHarnessState extends State<_ReorderHarness> {
  late List<RunStop> _stops = widget.stops;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          children: [
            SizedBox(
              height: 200,
              child: RoutePreviewMap(stops: _stops, depot: widget.depot),
            ),
            Expanded(
              child: ReorderableListView.builder(
                buildDefaultDragHandles: false,
                itemCount: _stops.length,
                onReorderItem: (oldIndex, newIndex) {
                  setState(() {
                    final stops = [..._stops];
                    stops.insert(newIndex, stops.removeAt(oldIndex));
                    _stops = stops;
                  });
                },
                itemBuilder: (context, index) => ReorderableDelayedDragStartListener(
                  key: ValueKey(_stops[index].id),
                  index: index,
                  child: SizedBox(height: 80, child: Center(child: Text(_stops[index].customerName))),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

void _reorderTests() {
  final stops = [
    _stop('a', -45.87, 170.48, const []),
    _stop('b', -45.88, 170.49, const []),
    _stop('c', -45.89, 170.50, const []),
  ];
  const depot = LatLng(-45.86, 170.47);

  testWidgets('long-press dragging a card reorders the list and redraws the '
      'route through the new order', (tester) async {
    await tester.pumpWidget(
      const _ReorderHarness(stops: [], depot: depot).runtimeType == Never
          ? const SizedBox()
          : _ReorderHarness(stops: stops, depot: depot),
    );
    await tester.pump();

    List<LatLng> line() => tester.widget<PolylineLayer>(find.byType(PolylineLayer)).polylines.single.points;

    expect(line().sublist(1, 4), [stops[0].location, stops[1].location, stops[2].location]);

    // Pick up the third card and carry it to the top of the list.
    final gesture = await tester.startGesture(tester.getCenter(find.text('Customer c')));
    await tester.pump(kLongPressTimeout + const Duration(milliseconds: 100));
    // Moved in steps with a frame between each: a reorderable list shifts
    // its items as the drag travels, and a single jump lands against the
    // pre-shift layout (which drops the card one slot short).
    for (var i = 0; i < 10; i++) {
      await gesture.moveBy(const Offset(0, -18));
      await tester.pump();
    }
    await gesture.up();
    await tester.pumpAndSettle();

    // c first, and a/b pushed down by exactly one - not two, which is what a
    // doubled index fixup would produce.
    expect(line().sublist(1, 4), [stops[2].location, stops[0].location, stops[1].location]);
    expect(line().first, depot);
    expect(line().last, depot);
  });
}
