// File generated by FlutterFire CLI - re-running `flutterfire configure`
// overwrites this file entirely, so other Terraform-provisioned identifiers
// this app needs (that don't fit FirebaseOptions' fixed fields) live in
// config/infra_config.dart instead, where they survive regeneration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWLV57xQC7RFj3wosQtLaLp8k4DVhyjK4',
    appId: '1:146112277848:web:1f560dbe4fd168484b492d',
    messagingSenderId: '146112277848',
    projectId: 'video-gen-499408',
    authDomain: 'video-gen-499408.firebaseapp.com',
    databaseURL: 'https://video-gen-499408-default-rtdb.firebaseio.com',
    storageBucket: 'video-gen-499408.firebasestorage.app',
    measurementId: 'G-GZY9FW9W6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-I76K6bkYWaXsAHnsJuYA4sVF7-bf0Fo',
    appId: '1:146112277848:android:9bed9f0d5147442c4b492d',
    messagingSenderId: '146112277848',
    projectId: 'video-gen-499408',
    databaseURL: 'https://video-gen-499408-default-rtdb.firebaseio.com',
    storageBucket: 'video-gen-499408.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqbOoZA6Z0LXs8y0Zgb-vODBrdJduFv0A',
    appId: '1:146112277848:ios:fccf24563d9043a74b492d',
    messagingSenderId: '146112277848',
    projectId: 'video-gen-499408',
    databaseURL: 'https://video-gen-499408-default-rtdb.firebaseio.com',
    storageBucket: 'video-gen-499408.firebasestorage.app',
    iosClientId: '146112277848-lahjhsi6159i8ui7gvv9rlhf54aihb98.apps.googleusercontent.com',
    iosBundleId: 'com.delivery.dmmDelivery',
  );
}
