// File generated by FlutterFire CLI - re-running `flutterfire configure`
// overwrites this file entirely, so other Terraform-provisioned identifiers
// this app needs (that don't fit FirebaseOptions' fixed fields) live in
// config/infra_config.dart instead, where they survive regeneration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNtxo444tvMD4cp6x8oizewTf1SvpRLS4',
    appId: '1:815924295824:web:d5bf26e07ff2b977fcc015',
    messagingSenderId: '815924295824',
    projectId: 'i-destiny-428904-s2',
    authDomain: 'i-destiny-428904-s2.firebaseapp.com',
    databaseURL: 'https://i-destiny-428904-s2-default-rtdb.firebaseio.com',
    storageBucket: 'i-destiny-428904-s2.firebasestorage.app',
    measurementId: 'G-8M8325PJJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC06hW0xG8OVfH0Myq5NON91yXQAIT-80A',
    appId: '1:815924295824:android:60e97bcd3edee89dfcc015',
    messagingSenderId: '815924295824',
    projectId: 'i-destiny-428904-s2',
    databaseURL: 'https://i-destiny-428904-s2-default-rtdb.firebaseio.com',
    storageBucket: 'i-destiny-428904-s2.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0w4vFpwx5dfGzsmY4ynb8VLJHd3QIItI',
    appId: '1:815924295824:ios:f9aff9a5bbc08a79fcc015',
    messagingSenderId: '815924295824',
    projectId: 'i-destiny-428904-s2',
    databaseURL: 'https://i-destiny-428904-s2-default-rtdb.firebaseio.com',
    storageBucket: 'i-destiny-428904-s2.firebasestorage.app',
    iosBundleId: 'com.delivery.dmmDelivery',
  );
}
