// GENERATED by tool/generate_infra_config.sh - do not hand-edit.
// Re-run it after infra changes (bucket recreated, sign-in client rotated)
// instead of updating these values by hand. Sourced from live GCP/Firebase
// state, not from the backend repo's filesystem - see the script for why.
//
// Sources:
//   runSheetsBucket              <- process-run-sheet Cloud Function's
//                                    Storage trigger config
//                                    (project i-destiny-428904-s2, region us-west1)
//   googleSignInServerClientId   <- Firebase Auth's Google IdP config
//                                    (projects/i-destiny-428904-s2/defaultSupportedIdpConfigs/google.com)
//   riderBoardUrl                <- rider-board Cloud Function's URL
//                                    (project i-destiny-428904-s2, region us-west1)
class InfraConfig {
  InfraConfig._();

  /// The rider-board endpoint backing the Owner Maps screen. Called with the
  /// signed-in owner's Firebase ID token; the function verifies the token and
  /// the `role: owner` claim itself, since Cloud Run IAM can't.
  ///
  /// Empty when the function isn't deployed in the target project - callers
  /// must check rather than parsing it blindly.
  static const riderBoardUrl = 'https://us-west1-i-destiny-428904-s2.cloudfunctions.net/rider-board';

  /// The OAuth web client ID backing Firebase's Google sign-in provider.
  /// Not a secret (it's a public identifier apps embed directly), but
  /// Android's GoogleSignIn needs it explicitly as `serverClientId` to
  /// request an ID token Firebase can verify - without it,
  /// GoogleSignIn.instance.initialize() throws on Android.
  static const googleSignInServerClientId = '815924295824-t8s6cn1dpl948eimtcgm5kpbhvclivuc.apps.googleusercontent.com';

  /// The dedicated Storage bucket run sheet PDFs must land in - not the
  /// default firebase_options.dart bucket. process_run_sheet_upload_fn.py's
  /// Cloud Storage trigger and storage.rules' owner-only write rule are
  /// only bound to this bucket; uploading to the default bucket instead
  /// silently never triggers processing.
  static const runSheetsBucket = 'gs://i-destiny-428904-s2-run-sheets-f9d5d1';
}
